const collectorType = {
  CAMPAIGN_MANAGER: "CAMPAIGN_MANAGER",
  CAMPAIGN_MANAGER_CREATIVE: "CAMPAIGN_MANAGER_CREATIVE",
  DISPLAY_VIDEO_360: "DISPLAY_VIDEO_360",
};

module.exports = collectorType;
